/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 */
// const LCAPApplicationService = require('@sap/low-code-event-handler');
// const purchaseorders_Request_Logic = require('./code/purchaseorders-request-logic');

// class podemoService extends LCAPApplicationService {
//     async init() {

//         this.before('CREATE', 'PurchaseOrders', async (request) => {
//             await purchaseorders_Request_Logic({
//                 request
//             });
//         });

//         return super.init();
//     }
// }


// module.exports = {
//     podemoService
// };


const cds = require('@sap/cds')

/**
 * Implementation for Risk Management service defined in ./risk-service.cds
 */
module.exports = cds.service.impl(async function() {
    
   

    this.before('CREATE', 'PurchaseOrders', async req => {
        data = req.data;
	    data.RequestId = 'PR0001';
        // const tx = cds.transaction(req)
        // return bupa.run(req.query);
    });

    // this.after('READ', 'Risks', risksData => {
    //     const risks = Array.isArray(risksData) ? risksData : [risksData];
    //     risks.forEach(risk => {
    //         if (risk.impact >= 100000) {
    //             risk.criticality = 1;
    //         } else {
    //             risk.criticality = 2;
    //         }
    //     });
    // });
});